#!/usr/bin/env python3
"""
Extract secrets from /Users/maraneweda/config/*.rtf into a single local env
file at ~/.config/kuwai-agent.env (chmod 600), OUTSIDE the build repo. No
secret value is ever echoed to stdout, returned, logged, or committed. The
file is gitignored by the build repo .gitignore.

Operator runs this on the build machine only. The same env shape is later
SCP'd into /etc/kuwai/agent.env on the VPS (root-only).
"""
from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path

CONFIG = Path("/Users/maraneweda/config")
OUT = Path.home() / ".config" / "kuwai-agent.env"


def _rtf_to_text(p: Path) -> str:
    if not p.is_file():
        return ""
    if p.suffix.lower() == ".rtf":
        try:
            return subprocess.check_output(
                ["textutil", "-convert", "txt", "-stdout", str(p)],
                text=True)
        except Exception:
            return ""
    return p.read_text(encoding="utf-8", errors="ignore")


def _find(text: str, *patterns: str) -> str | None:
    for rx in patterns:
        m = re.search(rx, text)
        if m:
            return m.group(1) if m.groups() else m.group(0)
    return None


def _alpaca_pair(text: str) -> tuple[str | None, str | None]:
    # Alpaca key id is typically PK... (paper) or AK... (live), 20 chars
    # alphanumeric. Secret is 40 chars base64-ish. Be tolerant of paste format.
    key = _find(text,
                r"\b(PK[A-Z0-9]{16,22})\b",
                r"\b(AK[A-Z0-9]{16,22})\b",
                r"key[^\n]*?[:= ]\s*([A-Z0-9]{18,24})",
                )
    sec = _find(text,
                r"\b([A-Za-z0-9/+]{36,48})\b(?![A-Za-z0-9/+])",
                r"secret[^\n]*?[:= ]\s*([A-Za-z0-9/+]{36,48})",
                )
    # Exclude pure-hex tokens (commit shas / digests) from the secret heuristic
    if sec and re.fullmatch(r"[0-9a-fA-F]{36,48}", sec):
        sec = None
    return key, sec


def _anthropic(text: str) -> str | None:
    return _find(text, r"(sk-ant-[A-Za-z0-9_-]{20,})")


def _apify(text: str) -> str | None:
    return _find(text,
                 r"(apify_api_[A-Za-z0-9]{16,})",
                 r"(?:^|\s)([A-Za-z0-9]{32,80})(?:\s|$)")


def _hostinger(text: str) -> str | None:
    # Hostinger v1 personal access tokens look like long opaque strings.
    # Be permissive: take the longest non-whitespace token of length >= 32.
    cands = re.findall(r"\S{32,}", text)
    cands = [c for c in cands if not re.fullmatch(r"\W+", c)]
    return max(cands, key=len) if cands else None


def main() -> int:
    OUT.parent.mkdir(parents=True, exist_ok=True)

    paper = _rtf_to_text(CONFIG / "Alpaca" / "token (paper).rtf")
    live = _rtf_to_text(CONFIG / "Alpaca" / "token (live).rtf")
    anthr = _rtf_to_text(CONFIG / "Anthropic" / "API.rtf")
    apify_txt = (_rtf_to_text(CONFIG / "Apify" / "token.rtf")
                 + "\n" + _rtf_to_text(CONFIG / "Apify" / "token"))
    hostinger = _rtf_to_text(CONFIG / "Hostinger" / "tokens.rtf")

    pk, ps = _alpaca_pair(paper)
    lk, ls = _alpaca_pair(live)
    ak = _anthropic(anthr) or _anthropic(_rtf_to_text(
        CONFIG / "Anthropic" / "token.json"))
    af = _apify(apify_txt)
    ht = _hostinger(hostinger)

    found = {
        "APCA_PAPER_KEY_ID": bool(pk),
        "APCA_PAPER_SECRET":  bool(ps),
        "APCA_LIVE_KEY_ID":   bool(lk),
        "APCA_LIVE_SECRET":   bool(ls),
        "ANTHROPIC_API_KEY":  bool(ak),
        "APIFY_TOKEN":        bool(af),
        "HOSTINGER_API_TOKEN": bool(ht),
    }
    print("# secret presence (no values printed):")
    for k, v in found.items():
        print(f"#   {k}: {'present' if v else 'MISSING'}")

    lines = [
        "# ~/.config/kuwai-agent.env -- LOCAL ONLY, chmod 600, NEVER commit",
        "# Generated by build_tools/load_secrets.py from /Users/maraneweda/config/",
        "# These are the runtime secrets for the local paper-cycle sanity",
        "# preview and later get scp'd to /etc/kuwai/agent.env on the VPS.",
        f"APCA_PAPER_KEY_ID={pk or ''}",
        f"APCA_PAPER_SECRET={ps or ''}",
        f"APCA_LIVE_KEY_ID={lk or ''}",
        f"APCA_LIVE_SECRET={ls or ''}",
        f"ANTHROPIC_API_KEY={ak or ''}",
        f"APIFY_TOKEN={af or ''}",
        f"HOSTINGER_API_TOKEN={ht or ''}",
        # KUWAI_MODE default is paper; only Maran's go-live step sets live
        "KUWAI_MODE=paper",
        # synthetic E0 used ONLY for the local/VPS paper cycle. The real E0 is
        # captured at the Maran-triggered seal step from the live account.
        "KUWAI_E0=200.0",
        # Block N is sealed-config but the named-list is empty pending Maran
        # (see EXECUTION-TERMINAL-STATUS). KUWAI_LIVE_BLOCK_N=0 means do not
        # live-scrape during paper.
        "KUWAI_LIVE_BLOCK_N=0",
    ]
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    os.chmod(OUT, 0o600)
    # Be paranoid about contents being readable later via another tool: do
    # NOT print the file path's contents and do NOT exit nonzero just for a
    # missing secondary (apify) token; do exit nonzero if a required one is
    # missing (paper key + anthropic).
    if not (pk and ps and ak):
        sys.stderr.write("FATAL: required paper-Alpaca or Anthropic key missing\n")
        return 2
    print(f"# wrote {OUT} (chmod 600)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
